services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mysql
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "8000:8000"
    networks:
      - app
    volumes:
      - .:/app

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=casamento
      - MYSQL_USER=neves
      - MYSQL_PASSWORD=12qwaszx
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

volumes:
  mysql_data:

networks:
  app:
    driver: bridge
